// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgo76GepbDRRXyeue74qj2QKU3CPErU-Q',
    appId: '1:746091179193:web:cc8e16435a08183209ff68',
    messagingSenderId: '746091179193',
    projectId: 'lugat-b17bf',
    authDomain: 'lugat-b17bf.firebaseapp.com',
    storageBucket: 'lugat-b17bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpxezisVdDOBHpEC2-b7BXfzhiiNfcsM',
    appId: '1:746091179193:android:d386523a0e9f473b09ff68',
    messagingSenderId: '746091179193',
    projectId: 'lugat-b17bf',
    storageBucket: 'lugat-b17bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcEaIb09Zc_ssGooMFb0VDZr46S6Dff4I',
    appId: '1:746091179193:ios:45f90428b30aa39009ff68',
    messagingSenderId: '746091179193',
    projectId: 'lugat-b17bf',
    storageBucket: 'lugat-b17bf.appspot.com',
    iosClientId: '746091179193-g4pem0gtsvbnfi0so4fcm8ptcd6qbd3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lugatAdmin',
  );
}
